<<<<<<< HEAD
# Generated by Django 2.2.5 on 2019-09-09 20:51
=======
# Generated by Django 2.1.2 on 2019-03-03 02:27
>>>>>>> 8ef656553446a01c279f0b34583b1507b163af7b

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
